export const LANDING = '/';
export const HOME = '/home';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const PASSWORD_FORGET = '/pw-forget';
export const GAMES = '/games';
export const GAME = '/game/:id';
export const GAME_WITH_ID = (id) => `/game/${id}`;
